package com.ls.l7mall_2.mapper;

import com.ls.l7mall_2.entity.Cart;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l7mall_cart
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l7mall_cart
     *
     * @mbggenerated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l7mall_cart
     *
     * @mbggenerated
     */
    int insertSelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l7mall_cart
     *
     * @mbggenerated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l7mall_cart
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l7mall_cart
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cart record);
    public List<Cart> selectCartByUserId(Integer userId);
    public int getAllCheckedByUserId(Integer userId);
    public Cart selectByUserIdAndProductId(@Param("userId") Integer userId, @Param("productId") Integer productId);
    public int deleteByUserIdAndProductIds(@Param("userId") Integer userId, @Param("productIds") List<String> productIds);
    public int updateCheckedByUserId(@Param("userId") Integer userId, @Param("productId")Integer productId,@Param("checked")Integer checked);
    public int getCartProductCount(@Param("userId") Integer userId);
    public List<Cart> selectCartCheckedByUserId(Integer userId);
}