package com.ls.l7mall_2.mapper;

import com.ls.l7mall_2.entity.User;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l7mall_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l7mall_user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l7mall_user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l7mall_user
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l7mall_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table l7mall_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);

    // 校验用户名是否存在
    public int checkUsername(String username);
    // 根据用户名和用户密码查找用户
    public User selectToLogin(@Param("username") String username, @Param("password")String password);
    // 校验email是否存在
    public int checkEmail(String email);
    // 查找安全问题
    public String selectQuestion(String username);
    // 查找答案
    public int selectAnswer(@Param("username")String username, @Param("question")String question, @Param("answer")String answer);
    // 修改密码
    public int updatePassword(@Param("username")String username,@Param("password")String password);
    // 原密码是否正确
    public int checkPasword(@Param("userId") Integer userId,@Param("password") String password);
    // 校验新的email是否被使用
    public int checkEmailById(@Param("userId") Integer userId,@Param("email") String email);
    // 获取所有的用户信息
    public List<User> selectAll();  
    
}